### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by dignite**
https://www.gitignore.io/

**In order** to allow local settings in VSCode
**And** to easily maintain coming updates of `.gitignore`
**We want** to update `.gitignore` clearly with the recommended settings from [gitignore.io](https://www.gitignore.io/)
**And** the selected presets should be `Node` and `Code` for now

### CODE REVIEW

**Comment by allan-stewart** [comment]
This PR is another one that was knocked out by the rewriting of history. But I'm torn on it. On the one hand, I can see where it could be useful to get back in if people are using tooling that generates those files. On the other hand, I personally favor an ignore-as-you-go YAGNI approach. I'm sure we could enumerate many things that should never be committed, but if nobody ever uses `nuxt.js` for the mob-timer (for example) does that actually help?

**Comment by dignite** [comment]
In general I am also a fan of YAGNI but I have personally never regretted using .gitignore.io since the generated part is clearly marked and it is fire and forget. It's like we are using a library where we don't need to call every function. :)

**Comment by allan-stewart** [comment]
Your analogy is having the opposite effect on me.

If you pull in a library, no you don't need to call every function. But hopefully the bulk of that library is useful, otherwise you're dragging along waste and increasing your liability. If you're only calling one or two things in that library then maybe you've got the wrong library.

That's what's making my spider-sense tingle here... it just feels like .the .gitignore.io suggested a lot more stuff than I'd expect to ever need to ignore.

BUT this isn't a library... it's just a .gitignore file. So probably fine? I just wanted to make sure I had at least voiced my thought on it, just in case it resonated. When people say everything is all pros and leave out the cons, it makes me not trust the thing. 😄

**Comment by dignite** [comment]
Fair point, a library that is barely used is a bad sign :) It's cost vs benefit and a library has a performance cost, cognitive load cost etc.

**Pull request merged**
