### PR TITLE
Adds Linux build script, application icon

### PR DESCRIPTION
**Pull request by picandocodigo**
I'm using the app in Debian Testing with GNOME 3.22.3. Everything seems to work fine and the tests run fine.

I added the icon for GNOME's (and theoretically Unity's and other Desktop Environment's) task bars:
mob-timer-icon

Let me know if you need any further testing or more information.

### CODE REVIEW

**Comment by mattcbaker** [comment]
@picandocodigo I haven't had a chance to run this yet, but what do you think about moving `icon.png`  into `/src/windows/img`?

**Comment by picandocodigo** [comment]
@mattcbaker I've updated the PR to have `icon.png` in `/src/windows/img`. I initially had it on the project's root because the icons for Mac and Windows are there. But since it's a png file, maybe it makes sense to have it under `img`.

**Comment by allan-stewart** [comment]
I had originally put the icons in the root folder because they were only being used in the build process. So I get why you used it there; that makes sense. Looks like you copied the file based on Matt's suggestion, that's good too.

Overall this looks great to me. I'm gonna merge it. Thanks for contributing, and I hope the timer has been useful for you and your team, @picandocodigo !

**Comment by picandocodigo** [comment]
Awesome! Yeah, my coworkers were using it on Mac, and when I saw it was an electron app I figured there would be a way to make it run on Linux. Luckily it was pretty simple 😃

**Pull request merged**
